services:
###########################################################################
### Default configuration for this services
### TODO: Should be changed
###########################################################################
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

###########################################################################
### App Forms
###########################################################################
    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }

    app.form.user:
            class: AppBundle\Form\UserType
            tags:
                - { name: form.type, alias: app_user_form }

###########################################################################
### App Listeners
###########################################################################
    app.registration_listener:
        class: AppBundle\EventListener\UserRegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }